services:
    app.controller.abstract:
        abstract: true
        class: Infrastructure\Bundle\AppBundle\Controller\AbstractUserController
        arguments: ['@twig','@tactician.commandbus','@form.factory','@router']

    app.controller.home:
        class: Infrastructure\Bundle\AppBundle\Controller\HomeUserController
        parent: app.controller.abstract

    app.controller.create:
        class: Infrastructure\Bundle\AppBundle\Controller\CreateUserController
        parent: app.controller.abstract

    app.controller.show:
        class: Infrastructure\Bundle\AppBundle\Controller\ShowController
        parent: app.controller.abstract

    app.controller.delete:
        class: Infrastructure\Bundle\AppBundle\Controller\DeleteController
        parent: app.controller.abstract
