services:
    user.repository:
        class: Infrastructure\User\UserRepository
        public: false
        arguments: ['@app.doctrine.manager_registry_facade', 'Model:User\User']

    app.user.command_handler.create:
        class: Application\Command\User\CreateUserCommandHandler
        arguments: ['@user.repository']
        tags:
            - { name: tactician.handler, command: Application\Command\User\CreateUserCommand }

    app.user.command_handler.remove:
        class: Application\Command\User\DeleteUserCommandHandler
        arguments: ['@user.repository']
        tags:
            - { name: tactician.handler, command: Application\Command\User\DeleteUserCommand }

    app.user.query_handler.create:
        class: Application\Query\UserQueryHandler
        arguments: ['@user.repository']
        tags:
            - { name: tactician.handler, command: Application\Query\UserQuery }

    app.user.query_handler.show:
        class: Application\Query\ShowUserQueryHandler
        arguments: ['@user.repository']
        tags:
            - { name: tactician.handler, command: Application\Query\ShowUserQuery }