services:
    user.repository:
        class: Infrastructure\User\UserRepository
        public: false
        arguments: ['@app.doctrine.manager_registry_facade', 'Model:User\User']

    app.user.command_handler.create:
        class: Application\Command\User\CreateUserCommandHandler
        arguments: ['@user.repository']
