user_index:
    path:     /
    defaults: { _controller: app.controller.home:indexAction }
    methods:  GET

#user_show:
#    path:     /{id}/show
#    defaults: { _controller: "AppBundle:User:show" }
#    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: app.controller.create:createUser }
    methods:  [GET, POST]

#user_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "AppBundle:User:edit" }
#    methods:  [GET, POST]
#
user_delete:
    path:     /{id}/delete
    defaults: { _controller: app.controller.create:deleteAction }
    methods:  GET
