user_index:
    path:     /
    defaults: { _controller: app.controller.home:indexAction }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: app.controller.show:showAction }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: app.controller.create:createAction }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: app.controller.edit:editAction }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: app.controller.delete:deleteAction }
    methods:  GET
