Infrastructure\Bundle\AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Infrastructure\Bundle\AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
    lifecycleCallbacks: {  }
